name: Delete branch

on:
  pull_request:
    branches: [develop]
    types: [closed]

permissions:
  contents: write

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
